# Generated by Django 4.0.4 on 2022-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='musicstore.cartproduct', verbose_name='Продукты для корзины'),
        ),
    ]
